name: 'AI Code Reviewer (AiReviewPR)'
description: 'Perform code review using openai API'
author: kekxv

inputs:
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
  BASE_REF:
    description: 'github event pull_request base ref'
    default: ${{ github.event.pull_request.base.ref }}
  PULL_REQUEST_NUMBER:
    description: 'github event pull_request number'
    default: ${{ github.event.pull_request.number }}
  CHINESE:
    description: 'use chines 作废'
    default: ""
  LANGUAGE:
    description: 'use chines'
    default: "Chinese"
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.


      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.


      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
  model:
    description: 'AI model to use for code review (e.g., gemma3:12b, gpt-4o)'
    required: true
    default: 'gemma3:12b'
  host:
    description: 'ollama host or openai base url'
    required: true
    default: 'http://127.0.0.1:11434'
  PROMPT_GENRE:
    description: 'prompt genre'
    default: ' '
  reviewers_prompt:
    description: 'system prompt'
    required: false
    default: ""
  ai_token:
    description: 'ai token (API Key) for OpenAI or authenticated Ollama'
    required: false
    default: " "
  include_files:
    description: 'Comma-separated list of files to include review'
    required: false
    default: " "  # 默认为空，表示不限制
  exclude_files:
    description: 'Comma-separated list of files to exclude review'
    required: false
    default: " "  # 默认为空，表示不传递文件
  EVENT_ACTION:
    description: 'The event action (e.g., opened, synchronize)'
    default: ${{ github.event.action }}
  EVENT_BEFORE:
    description: 'The previous commit SHA (for incremental diffs)'
    default: ${{ github.event.before }}
  REVIEW_PULL_REQUEST:
    description: 'Force full review? true=Check all files; false=Check only changed files in this push'
    default: "false"
runs:
  using: node20
  main: 'dist/index.js'
